"""add discord servers

Revision ID: 6fb7f87d8671
Revises: 10807a5d65b9
Create Date: 2023-12-20 21:38:39.121783

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# Polar Custom Imports
from polar.kit.extensions.sqlalchemy import PostgresUUID

# revision identifiers, used by Alembic.
revision = "6fb7f87d8671"
down_revision = "10807a5d65b9"
branch_labels: tuple[str] | None = None
depends_on: tuple[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "discord_servers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("guild_id", sa.String(length=64), nullable=False),
        sa.Column("guild_name", sa.String(length=256), nullable=False),
        sa.Column("guild_icon", sa.String(length=256), nullable=False),
        sa.Column("access_token", sa.String(length=1024), nullable=False),
        sa.Column("expires_at", sa.Integer(), nullable=True),
        sa.Column("refresh_token", sa.String(length=1024), nullable=True),
        sa.Column(
            "guild_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("discord_servers_organization_id_fkey"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("discord_servers_pkey")),
        sa.UniqueConstraint(
            "organization_id", name=op.f("discord_servers_organization_id_key")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("discord_servers")
    # ### end Alembic commands ###
