"""normalize discord bot

Revision ID: 1fe16c92d06c
Revises: 6fb7f87d8671
Create Date: 2023-12-21 15:23:41.048052

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# Polar Custom Imports
from polar.kit.extensions.sqlalchemy import PostgresUUID

# revision identifiers, used by Alembic.
revision = "1fe16c92d06c"
down_revision = "6fb7f87d8671"
branch_labels: tuple[str] | None = None
depends_on: tuple[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("discord_servers")
    op.add_column(
        "organizations",
        sa.Column("discord_guild_id", sa.String(length=64), nullable=True),
    )
    op.add_column(
        "organizations",
        sa.Column(
            "discord_bot_connected_at", sa.TIMESTAMP(timezone=True), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("organizations", "discord_bot_connected_at")
    op.drop_column("organizations", "discord_guild_id")
    op.create_table(
        "discord_servers",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "modified_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "deleted_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "guild_id", sa.VARCHAR(length=64), autoincrement=False, nullable=False
        ),
        sa.Column(
            "guild_name", sa.VARCHAR(length=256), autoincrement=False, nullable=False
        ),
        sa.Column(
            "guild_icon", sa.VARCHAR(length=256), autoincrement=False, nullable=False
        ),
        sa.Column(
            "access_token", sa.VARCHAR(length=1024), autoincrement=False, nullable=False
        ),
        sa.Column("expires_at", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "refresh_token", sa.VARCHAR(length=1024), autoincrement=False, nullable=True
        ),
        sa.Column(
            "guild_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("organization_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name="discord_servers_organization_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="discord_servers_pkey"),
        sa.UniqueConstraint(
            "organization_id", name="discord_servers_organization_id_key"
        ),
    )
    # ### end Alembic commands ###
